### ISSUE TITLE
Incompatibility issue with Zbu.ModelsBuilder

### ISSUE THREAD

**Issue by Korayem** [mattbrailsford/umbraco-vorto#33]
Any Vorto property causes failure when building POCO models in Zbu.ModelsBuilder giving this error
> CS0122: 'Our.Umbraco.Vorto.Models.VortoValue' is inaccessible due to its protection level 

I checked the code and found that `VortoValue` is marked as `internal` in [VortoValue.cs](https://github.com/mattbrailsford/umbraco-vorto/blob/395688dc027e60998503c6927b131b96bc24477b/Src/Our.Umbraco.Vorto/Models/VortoValue.cs)

**Comment by mattbrailsford** [comment]
VortoValue is now public and just made constructor internal. Can you confirm if this fixes the issue? I'm unfamiliar with ModelsBuilder

**Comment by jbreuer** [comment]
As a workaround you can override the Models Builder property in a partial class. Just like in this example: http://24days.in/umbraco/2015/multilingual-vorto-nested-content/

**Comment by mattbrailsford** [comment]
As I've had no feedback on this from my original update, I'm going to close it down. If you end up doing some tests that prove it's still broken, please feel free to reopen the issue.
