### ISSUE TITLE
HasVortoValue does not work if string is empty

### ISSUE THREAD

**Issue by tommyTanaka** [mattbrailsford/umbraco-vorto#40]
Just noticed I get an Macro Render Error if the Sting is empty and I call HasVortoValue

**Comment by mattbrailsford** [comment]
Could you please explain your setup and the code you are using so that I can replicate your circumstances?

**Comment by tommyTanaka** [comment]
Create a Voto-Datatype:

Data-type: Textstring
Lang-Source: Installed
XPath: empty
Display Native: not selected
Primary Lang: German
Mand. Field: Ignore
RTL: Ignore
Hide Label: not selected

I get a Render Macro Error, if I do not fill out the textstring-Field.

Code in my Macro:

if(Model.Content.HasVortoValue("linkZuTwitter", recursive: true))
	{
...
}

Also happens, if I remove the recursive:true Property.

**Comment by mattbrailsford** [comment]
Where does the Macro part come into it? I don't get why you'd be getting a Macro error? Is that vorto code located directly in a template .cshtml file? or inside a macro? Is that property you've defined an the page doc type you are rendering? or are you using it along side nested content? or doc type grid editor? (you mentioned the grid on twitter) If so, how is this all linked?

**Comment by tommyTanaka** [comment]
The PartialView-Macro-Part is rendered in my Master-Template:

@Umbraco.RenderMacro("RenderBodyStartScript")

"linkZuTwitter" is just a vorto doctype Property in my MainPage, that's why I do the recursive call.

The vorto-code is located in a Partial View Macro File under the developer-section.

**Comment by tommyTanaka** [comment]
Ok, this is the exception I get:

> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>    bei Our.Umbraco.Vorto.Extensions.VortoValueExtensions.FindBestMatchCulture(VortoValue value, String cultureName)
>    bei Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.DoInnerHasVortoValue(IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive)
>    bei Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.HasVortoValue(IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, String fallbackCultureName)
>    bei ASP._Page_Views_MacroPartials_RenderBodyStartScript_cshtml.Execute() in c:\inetpub\wwwroot\umbHbiG\Views\MacroPartials\RenderBodyStartScript.cshtml:Zeile 25

**Comment by mattbrailsford** [comment]
Fixed in commit 0661ba4. Updated build can be found here https://ci.appveyor.com/project/mattbrailsford/umbraco-vorto/build/1.5.0.26/artifacts

**Comment by tommyTanaka** [comment]
Great! Seems to work perfect now.
