### ISSUE TITLE
Conversion error - improper data in DB

### ISSUE THREAD

**Issue by ryanology** [mattbrailsford/umbraco-vorto#43]
I have some Vorto datatypes, which use the Textstring as the data type to wrap.  I'm getting a bunch of errors in the logs relating to these datatypes, such as:
ERROR Our.Umbraco.Vorto.Web.PropertyEditors.VortoPropertyEditor+VortoPropertyValueEditor - Error converting DB value to String
System.NullReferenceException: Object reference not set to an instance of an object.
   at Our.Umbraco.Vorto.Web.PropertyEditors.VortoPropertyEditor.VortoPropertyValueEditor.ConvertDbToString(Property property, PropertyType propertyType, IDataTypeService dataTypeService)

I put in some debugging (mainly spitting out the property data) and found that the error is coming from line 152 in VortoPropertyEditor.cs.  I've seen 2 strange property data values:

{   "dtdguid": "a8a879d3-69f0-43fd-aab0-07523fbd5286"  }
and
{   "dtdGuid": "a8a879d3-69f0-43fd-aab0-07523fbd5286",   "dtdguid": "a8a879d3-69f0-43fd-aab0-07523fbd5286"   }

I checked the cmsPropertyData table in the DB and found that it happens whenever a Vorto-wrapped Textstring is left blank.  If I put in any text, it's fine, but when left blank I get that incorrect data.  So it seems that it's not working properly when wrapping a Textstring type in Vorto and leaving it blank.

**Comment by mattbrailsford** [comment]
What version of Vorto are you using?

**Comment by ryanology** [comment]
1.5.1 with Umbraco 7.4.1.

**Comment by StephenWRogers** [comment]
I've got a similar issue - values in the db with multiple dtdGuid entries and no values.

Using 1.5.1 with Umbraco 7.4.1

From what I can see when saving an empty property lines 189 - 198 of vorto.js will check for empty properties and strip them out. 

```javascript

var cleanValue = {};
_.each($scope.languages, function(language) {
    if ($scope.model.value.values[language.isoCode] && JSON.stringify($scope.model.value.values[language.isoCode]).length > 0) {
        cleanValue[language.isoCode] = $scope.model.value.values[language.isoCode];
    }
});
$scope.model.value.values = !_.isEmpty(cleanValue) ? cleanValue : undefined;
```

So you end up with

`$scope.model.value.values = undefined;`

This is posted as the following with no values attribute

`{"id":223764,"alias":"keywords","value":{"dtdGuid":"125aed02-61e0-4431-b272-5a6525786f4b"}}`

This also causes problems when read back out - line 140 of VortoPropertyEditor.cs is

`var keys = value.Values.Keys.ToArray();`

where value.Values will == null


It seems like the second time you submit an empty box you end up with the multiple dtdGuid entries - but I've not looked too much into that yet.

Not sure the purpose of setting $scope.model.value.values to undefined as far as how to fix it?

Stephen

**Comment by ryanology** [comment]
Hey Matt,

Just wondering if you were able to replicate this or if you have found any resolution.  I currently have some custom data resolvers for Courier that this is messing with because of the null values.

Thanks

**Comment by StephenWRogers** [comment]
I have tried changing line 197 in vorto.js to 

`$scope.model.value.values = !_.isEmpty(cleanValue) ? cleanValue : {};` 

and some very light testing seems to have it working better and not corrupting the values. Not sure I'm confident enough in it to submit a PR, but it's working for me at the moment

That's not going to fix the data already in the DB though, seems like that's going to need cleaned up manually.

Stephen

**Comment by mattbrailsford** [comment]
Sorry guys, I've been absolutely stacked recently so haven't had chance to look into it yet. I'll try and find some time tomorrow to take a look. Do post any other comments you have / code tweaks you have as it'll make it much easier for me to diagnose the issue.

**Comment by mattbrailsford** [comment]
Ok, I think I've fixed the issue. It's not really a problem having the JS store undefined in the DB, and in fact I do this on purpose to minimise the amount of data in the db (why store "{}" when you can store "").

I've made a couple of changes though which are 1) standardise the spelling of dtdGuid so that only 1 attribute is saved and 2) added null checks within VortoValueConverter to no bother trying to deserialize the inner values if there are no inner values to deserialize. The HasVortoValue and GetVortoValue methods should already be checking for null, so you shouldn't have a problem there (although I have added another explicit null check in those to be safe).

If you wanna give the nightly a try and let me know if it solves your issues? https://ci.appveyor.com/project/mattbrailsford/umbraco-vorto/build/1.5.2.41/artifacts

Matt
