### ISSUE TITLE
Vorto Dropdowns: Cannot read property 'en-GB' of undefined

### ISSUE THREAD

**Issue by rosudrag** [mattbrailsford/umbraco-vorto#45]
Hello,

I've a project that I've added Vorto to and changed most of the properties to Vorto ones.
However, dropdowns have been causing major issues by losing data when saving. I saw this was supposedly fixed on latest version 1.5.1 and this is where I am having the javascript issue:

![image](https://cloud.githubusercontent.com/assets/1159700/14286623/a02c4078-fb47-11e5-84f3-8090b7ee25ec.png)

![image](https://cloud.githubusercontent.com/assets/1159700/14286633/a6213934-fb47-11e5-9514-d3e94722990b.png)

**Comment by mattbrailsford** [comment]
Please try and latest nightly and let me know if the problem persists

https://ci.appveyor.com/project/mattbrailsford/umbraco-vorto/build/artifacts

**Comment by rosudrag** [comment]
I've used the nightly with a umbraco 7.2.3 and 7.4.2 and same js errors.

**Comment by mattbrailsford** [comment]
ok, then I'll need to re-look into this. Which version of Umbraco are you using?

**Comment by rosudrag** [comment]
I'm using 7.2.3 for my stable version.

As stated earlier, I did an experimental upgrade to 7.4.2 and tried the nightly build also with that but have had same results.

**Comment by mattbrailsford** [comment]
ok, will take a look as soon as I can.

**Comment by rosudrag** [comment]
Thanks! Let me know if you need me to provide more debug info.

**Comment by mattbrailsford** [comment]
Hi @rosudrag 

I've just take a look at this in 7.4.2 using my local version (aka the nightly) and the dropdown is working perfectly fine for me. Selections are remembered between tab loads and after publish on page load. The values also return perfectly fine on the front end so I don't seem to be able to replicate this at all.

Can you make sure if you are updating to the nightly that you clear your JS cache as maybe you have a cached file from the previous version, but otherwise I can't think what the issue would be.

**Comment by rosudrag** [comment]
I will setup a new basic umbraco solution and test it. I'll come back with my results.

**Comment by rosudrag** [comment]
New instance with Vorto works as you would expect. I guess the issue lies somewhere between upgrading from 1.4.0 to the nightly build on my solution. I'll dig into it more and see what needs done on the upgrade.

**Comment by rosudrag** [comment]
I was unable to find anything that would point why I would be getting those JS errors. I've downgraded back to 1.4.0 and replaced all the Vorto Dropdowns with normal umbraco dropdowns until I figure it out ...

Console error log file:
http://puu.sh/o8exX/e4fa460079.log

**Comment by mattbrailsford** [comment]
Gonna close this issue then for the time being. Feel free to re-open if you find out the specific issue.
