### ISSUE TITLE
Creating nodes with Vorto properties from code

### ISSUE THREAD

**Issue by vsshs** [mattbrailsford/umbraco-vorto#49]
Hey, 

I am trying to create nodes from code. These nodes have e.g VortoTextField (aka TextString wrapped in Vorto).

Are there any guidelines on how to set the values for all languages? 

I found this: #9 , but maybe there were some changes regarding the model classes (VortoValue still seems to be internal)

**Comment by stefchri** [comment]
See #9 , I added a comment for creating content in stead of updating. I did edit the VortoValue class to have a public constuctor.

For all languages you could query all the languages as usual and just add them to the VortoValue model with corresponding values.

**Comment by mattbrailsford** [comment]
Have made VortoValue constructor public to help with this
