### ISSUE TITLE
Content dosn't render properly

### ISSUE THREAD

**Issue by lele7** [mattbrailsford/umbraco-vorto#51]
In 7.3.4 if I switch the language... the content of the grid dosn't render properly.

![image](https://cloud.githubusercontent.com/assets/8255641/15814811/42192e8a-2bc9-11e6-8cda-ad3ed9667f5d.png)

**Comment by mattbrailsford** [comment]
This is a core issue due to grid styles making assumptions of it's placement. See issue #50 for suggested work around.

**Comment by runegronkjaer** [comment]
Hi Matt,

I don't think it has to do with the grid styles and issue #50. I get it as well and what happens is that:
1. You load the page and the grid displays fine wrapped in Vorto
2. You then change language the first time and everything displays fine in the new language.
3. You change back to the first language. Now the error from above will happen. The richtext editor will not load the tiny mce, like the screenshot above, and other grid editors will also not render.

I have tried looking through the Vorto code to find  where the magic is happening, but I can't really put my finger on it. Maybe the grid needs to be initialized again somehow?

**Comment by lele7** [comment]
In my case this helps: 

you have to change this in the vorto.html file -  ng-if to ng-show
https://github.com/umco/umbraco-vorto/blob/master/src/Our.Umbraco.Vorto/Web/UI/App_Plugins/Vorto/views/vorto.html#L40

Sometimes the titles and specified elements aren't rended properly so you have to refresh the page or otherwise you have to do the suggested work around of matt. (the css styling stuff isn't loading properly)

I hope this helps.

**Comment by runegronkjaer** [comment]
Cool. I will check it out then.
