### ISSUE TITLE
ExamineIndex config for search

### ISSUE THREAD

**Issue by mrpeo** [mattbrailsford/umbraco-vorto#54]
How to setting custom field for index in Examine?

Now i can't search with field names in NestedContent field.

Please help this for search content in multi lang site!

Thanks you.

**Comment by mattbrailsford** [comment]
You'll have to hook into the Examine event GatheringNodeData and parse / seperate out the values manually and index them in custom fields. Unfortunately due to the complex nature of the data stored in Vorto / Nested Content, there is not automated way of doing this.
